<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="tailaideMBP" failures="2" tests="3" name="测试模块" time="0.034" errors="0" timestamp="30 7月 2024 10:23:56 GMT">
  <testcase classname="com.lxq.testOnline.testng.V1.test1" name="test1" time="0.01"/>
  <testcase classname="com.lxq.testOnline.testng.V1.test1" name="test2" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="1==2">
      <![CDATA[java.lang.IllegalArgumentException: 1==2
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
at com.lxq.testOnline.testng.V1.test1.test2(test1.java:18)
at com.lxq.testOnline.TestOnlineApplication.main(TestOnlineApplication.java:47)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.lxq.testOnline.testng.V1.test1" name="test3" time="0.0">
    <failure type="java.lang.RuntimeException" message="这是我自己的运行时异常">
      <![CDATA[java.lang.RuntimeException: 这是我自己的运行时异常
at com.lxq.testOnline.testng.V1.test1.test3(test1.java:25)
at com.lxq.testOnline.TestOnlineApplication.main(TestOnlineApplication.java:47)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- 测试模块 -->
